package com.example.demo.Enum;

public enum ModuleListingEnum {
	 LEADS, POLICIES, POLICIES_RENEWALS, PAYMENTS_REMINDERS, PROPOSALS,ENDORSEMENTS,CLAIMS,COVERAGES,CUSTOMERS,
	CUSTOMERS_CLAIMS,CUSTOMERS_ENDORSEMENTS,CUSTOMERS_POLICIES,CUSTOMER_POLICIES_RENEWALS;
}
